// <auto-generated />
using System;
using GestionPlazasVacantes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionPlazasVacantes.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionPlazasVacantes.Models.PlazaVacante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<bool>("ArmasObligatorio")
                        .HasColumnType("bit");

                    b.Property<bool>("ColegiaturaObligatoria")
                        .HasColumnType("bit");

                    b.Property<string>("Departamento")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EstadoFinal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("FechaLimite")
                        .HasColumnType("datetime2");

                    b.Property<string>("Horario")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LicenciaObligatoria")
                        .HasColumnType("bit");

                    b.Property<string>("NumeroConcurso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Requisitos")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("SalarioCompuesto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalarioGlobal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("SolicitarColegiatura")
                        .HasColumnType("bit");

                    b.Property<bool>("SolicitarLicencia")
                        .HasColumnType("bit");

                    b.Property<bool>("SolicitarPermisoArmas")
                        .HasColumnType("bit");

                    b.Property<bool>("SolicitarTitulos")
                        .HasColumnType("bit");

                    b.Property<string>("TipoConcurso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("TitulosObligatorios")
                        .HasColumnType("bit");

                    b.Property<int?>("UsuarioAsignadoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioAsignadoId");

                    b.ToTable("PlazasVacantes", "gestion");
                });

            modelBuilder.Entity("GestionPlazasVacantes.Models.Postulante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArchivoTitulosPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CurriculumPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("EstadoProceso")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ExperienciaLaboral")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("FormacionAcademica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormacionComplementaria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoColegiaturaPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FotoLicenciaPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FotoPermisoArmasPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FotoTituloPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Habilidades")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Idiomas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NumeroColegiatura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroPermisoArmas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtrosDatos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerfilProfesional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlazaVacanteId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TipoLicencia")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlazaVacanteId");

                    b.ToTable("Postulantes", "gestion");
                });

            modelBuilder.Entity("GestionPlazasVacantes.Models.SeguimientoPostulante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("Aprobado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("CumpleRequisitos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("EtapaActual")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("MotivoDescarte")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal?>("NotaPruebaTecnica")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("NotaPsicometrica")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<int>("PlazaVacanteId")
                        .HasColumnType("int");

                    b.Property<int>("PostulanteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlazaVacanteId");

                    b.HasIndex("PostulanteId");

                    b.ToTable("SeguimientosPostulantes", "gestion");
                });

            modelBuilder.Entity("GestionPlazasVacantes.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UltimoAccesoUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", "auth");
                });

            modelBuilder.Entity("GestionPlazasVacantes.Models.PlazaVacante", b =>
                {
                    b.HasOne("GestionPlazasVacantes.Models.Usuario", "UsuarioAsignado")
                        .WithMany("PlazasAsignadas")
                        .HasForeignKey("UsuarioAsignadoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UsuarioAsignado");
                });

            modelBuilder.Entity("GestionPlazasVacantes.Models.Postulante", b =>
                {
                    b.HasOne("GestionPlazasVacantes.Models.PlazaVacante", "PlazaVacante")
                        .WithMany("Postulantes")
                        .HasForeignKey("PlazaVacanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlazaVacante");
                });

            modelBuilder.Entity("GestionPlazasVacantes.Models.SeguimientoPostulante", b =>
                {
                    b.HasOne("GestionPlazasVacantes.Models.PlazaVacante", "PlazaVacante")
                        .WithMany()
                        .HasForeignKey("PlazaVacanteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GestionPlazasVacantes.Models.Postulante", "Postulante")
                        .WithMany()
                        .HasForeignKey("PostulanteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PlazaVacante");

                    b.Navigation("Postulante");
                });

            modelBuilder.Entity("GestionPlazasVacantes.Models.PlazaVacante", b =>
                {
                    b.Navigation("Postulantes");
                });

            modelBuilder.Entity("GestionPlazasVacantes.Models.Usuario", b =>
                {
                    b.Navigation("PlazasAsignadas");
                });
#pragma warning restore 612, 618
        }
    }
}
